// A screen saver that snows

#include <stdlib.h>

#include "orwin.h"

#define CHARSET    ((char*)0xB400) // $B400-B7FF
#define CHARDEF(C) ((char*)CHARSET+(C)*8)
#define ALTSET     ((char*)0xB800) // $B800-BB7F

typedef struct APP {
  char i;
} APP;

// character modifiers generated by Gemini

const char y[] = {
  0,0,0,0,0,0,1,2,3,4,5,6,7,7,7,7,7,7,6,5,4,3,2,1,
  1,1,1,1,2,3,4,5,6,6,6,6,5,4,3,2,
  2,2,2,3,4,5,5,5,4,3,2,3,4,4,3
};
const char x[] = {
  0,1,2,3,4,5,5,5,5,5,5,5,5,4,3,2,1,0,0,0,0,0,0,0,
  1,2,3,4,4,4,4,4,4,3,2,1,1,1,1,1,
  2,3,4,4,4,4,3,2,2,2,3,3,3,2,2
};

void flip(char* p) {
  char i, t;
  for (i = 0; i < 4; ++i) {
    t = p[i];
    p[i] = p[7 - i];
    p[7 - i] = t;
  }
}

void mirror(char* p) {
  char i, r, m;
  for (i = 0; i < 8; ++i) {
    r = p[i];
    m = 0;
    if (r & 0x20) m |= 0x01;
    if (r & 0x10) m |= 0x02;
    if (r & 0x08) m |= 0x04;
    if (r & 0x04) m |= 0x08;
    if (r & 0x02) m |= 0x10;
    if (r & 0x01) m |= 0x20;
    p[i] = m;
  }
}

void drop(char* p) {
  char c, r, m;
  char k[6] = {0, 0, 0, 0, 0, 0};
  for (r = 0; r < 8; ++r) {
    m = 0x20;
    for (c = 0; c < 6; ++c) {
      if (p[r] & m) {
        k[c]++;
      }
      m >>= 1;
    }
    p[r] = 0;
  }
  for (c = 0; c < 6; ++c) {
    m = 0x20 >> c;
    for (r = 0; r < k[c]; ++r) {
      p[7 - r] |= m;
    }
  }
}

void wind(char* p) {
  char r, b, c;
  for (r = 0; r < 8; ++r) {
    c = 0;
    for (b = 0x01; b <= 0x20; b <<= 1) {
      if (p[r] & b) c++;
    }
    p[r] = 0;
    for (b = 0; b < c; ++b) {
      p[r] |= (0x01 << b);
    }
  }
}

void melt(char* p) {
  char r, c, m, t = 0;
  for (r = 0; r < 8; ++r) {
    for (m = 0x01; m <= 0x20; m <<= 1) {
      if (p[r] & m) t++;
    }
    p[r] = 0;
  }
  r = 7;
  c = 0;
  while (t > 0) {
    p[r] |= (0x01 << c);
    t--;
    c++;
    if (c == 6) {
      c = 0;
      r--;
    }
  }
}

void vortex(char* p) {
  char r, m, t = 0, i;
  for (r = 0; r < 8; ++r) {
    for (m = 0x01; m <= 0x20; m <<= 1) {
      if (p[r] & m) t++;
    }
    p[r] = 0;
  }
  for (i = 0; i < t; ++i) {
    p[y[i]] |= (0x01 << x[i]);
  }
}

// memory corruption...
void rolling(char* p) {
  char r, b, m, f;
  do {
    f = 0;
    /* Scan from row 6 up to 0, checking the row directly below (r + 1) */
    for (r = 6; r >= 0; --r) {
      /* Extract bits that exist in current row but are empty in the row below */
      m = p[r] & ~p[r + 1];
      if (m) {
        p[r + 1] |= m; /* Drop them down */
        p[r] &= ~m;    /* Erase from old position */
        f = 1;         /* Mark that a change happened; loop again */
      }
    }
  } while (f);
}

// approximate...
void waitms(long w) {
  w <<= 3;
  while(--w>=0);
}

void snow(char* p) {
  char b, m, f;
  signed char r; /* MUST be signed so r >= 0 can turn false when r becomes -1 */
  do {
    f = 0;
    for (r = 6; r >= 0; --r) {
      m = p[r] & ~p[r + 1];
      if (m) {
        p[r + 1] |= m;
        p[r] &= ~m;
        f = 1;
      }
    }
    waitms(300);
  } while (f);
}

void snowpile(char* p) {
  char r, f, c, m, d, l, r_side;
  do {
    f = 0;
    for (r = 0; r < 7; ++r) {
      /* 1. Try falling straight down */
      m = p[r] & ~p[r + 1];
      if (m) {
        p[r + 1] |= m;
        p[r] &= ~m;
        f = 1;
	waitms(300);
        continue; /* Process next row if we successfully dropped straight down */
      }

      /* 2. Deteriorate spikes: Pixel is blocked from below, try sliding diagonally */
      c = p[r] & p[r + 1]; /* Candidates: pixels that HAVE a pixel directly beneath them */
      if (c) {
        for (d = 0; d < 6; ++d) {
          m = 0x01 << d; /* Isolate individual pixel column */
          if (c & m) {
            /* Check diagonal left (shift bit left to 0x02, 0x04...) */
            l = m << 1;
            /* Check diagonal right (shift bit right to 0x01...) */
            r_side = m >> 1;

            /* Slide left if within boundaries (<= 0x20) and both target slots are empty */
            if ((l <= 0x20) && !(p[r] & l) && !(p[r + 1] & l)) {
              p[r + 1] |= l;   /* Drop down-left */
              p[r] &= ~m;      /* Remove original */
              f = 1;
	      waitms(300);
              break;
            }
            /* Slide right if within boundaries (>= 0x01) and both target slots are empty */
            if ((r_side >= 0x01) && !(p[r] & r_side) && !(p[r + 1] & r_side)) {
              p[r + 1] |= r_side; /* Drop down-right */
              p[r] &= ~m;         /* Remove original */
              f = 1;
	      waitms(300);
              break;
            }
          }
        }
      }
    }
  } while (f);
}
  
void* app_snow(APP* app, char* line) {
  static char first= 1;
  static char m= 0;
  char c, b, i, *p;
  (void)line;

  if (!app) return calloc(sizeof(APP), 1);


  if (first) {
    first= 0;
    for(c=32; c<128; ++c) putchar(c);
  }

  if ((rand() % 100) > 3) return 0;
  
  // pick a char
  c= (rand() % 94) + 32;
  p= CHARDEF(c);
	 
  if (!m) m= (rand() % 8) + 1;
  
  m= 8;
  
  switch(m) {
  case 1: flip(p); break;
  case 2: mirror(p); break;
  case 3: drop(p); break;
  case 4: wind(p); break;
  case 5: melt(p); break;
  case 6: vortex(p); break;
  case 7: snow(p); break;
  case 8: snowpile(p); break;
  }

  //putchar(c+128);
  
  return 0;
}
