// A minimal VI - Mostly generated by Gemeni
// edited by Jonas S Karlsson

#include <stdio.h>
#include <conio.h>
#include <string.h>
#include <stdlib.h>

#include "orwin.h"


#define BUF_SIZE 2048

typedef struct APP {
  char* buf;
  int b_len, pos, cx, cy, ins;
  int last;
} APP;

void redraw(void* voidapp) {
  int i, x = 0, y = 0, pos= app->pos;
  char w, h, *buf= app->buf;

  screensize(&w, &h);

  // TODO: causes flickr, because of attrib
  clrscr();

  // TODO: use while(*p)
  for (i = 0; i < app->b_len; ++i) {
    if (i == pos) { app->cx = x; app->cy = y; }
    if (buf[i] == '\n') {
      x = 0; y++;
      if (y >= h - 1) break;
    } else {
      if (x < w) { gotoxy(x, y); putchar(buf[i]); x++; }
      if (x >= w) { x = 0; y++; }
      if (y >= h - 1) break;
    }
  }

  if (pos == app->b_len) { app->cx = x; app->cy = y; }
  gotoxy(0, h - 1);
  // TODO: goes bad, if toolong...
  printf("--- vi abcdefg");
  //printf("%-15s Pos:%d/%d", app->ins ? "-- INSERT --" : "-- COMMAND --", app->pos, app->b_len);
  gotoxy(app->cx, app->cy);
}

int next_line(void* voidapp, int p) {
  while (p < app->b_len && app->buf[p] != '\n') p++;
  return (p < app->b_len) ? p + 1 : app->b_len;
}

int prev_line(void* voidapp, int p) {
  if (p <= 0) return 0;
  p--; if (p > 0 && app->buf[p] == '\n') p--;
  while (p > 0 && app->buf[p-1] != '\n') p--;
  return p;
}

void* app_vi(void* voidapp, char* line) {
  char c;
  // cached
  char *buf;
  int pos, b_len;

  if (!app) {

    // TODO: combine into one
    app= calloc(sizeof(APP), 1);
    if (!app) return 0;
    app->buf= calloc(BUF_SIZE, 1);
    strcpy(app->buf, "Text\n  to\nedIt,");
    return app;

  } else if (line == CLEANUP) {
    free(app->buf); app->buf= NULL;
    return 0;
  }
  
  buf= app->buf;
  pos= app->pos;
  b_len= app->b_len;
  
  if (!buf) return WAITKEY;
		     
  c = getc();
  if (!c) return WAITKEY;
  
  if (app->ins) {
    if (c == 27) { app->ins = 0; if (pos > 0 && buf[pos-1] != '\n') pos--; }
    else if (c == 8 || c == 127) {
      if (pos > 0) { memmove(&buf[pos-1], &buf[pos], b_len - pos); pos--; b_len--; }
    } else if (b_len < BUF_SIZE - 1) {
      memmove(&buf[pos+1], &buf[pos], b_len - pos); buf[pos++] = (c == 13) ? '\n' : c; b_len++;
    }
  } else {
    if (c == 'i') app->ins = 1;
    else if (c == 'h' && pos > 0 && buf[pos-1] != '\n') pos--;
    else if (c == 'l' && pos < b_len && buf[pos] != '\n') pos++;
    else if (c == 'j') pos = next_line(app, pos);
    else if (c == 'k') pos = prev_line(app, pos);
    else if (c == 'x' && pos < b_len && buf[pos] != '\n') {
      memmove(buf+pos, buf+pos+1, b_len - pos - 1);
      b_len--;
    } else if (c == 'd') {
      if (app->last == 'd') {
	int start = prev_line(app, pos + 1), end = next_line(app, pos);
	memmove(buf+start, buf+end, b_len - end);
	b_len -= (end - start); pos = start; app->last = 0;
      }
      goto update;
    } else if (c == 'q') { clrscr(); return WAITKEY; } // TODO: exit

    app->last = 0;
  }

 update:
  app->pos= pos;
  app->b_len= b_len;

  redraw(app);
    
  return WAITKEY;
}
