// A minimal VI - Mostly generated by Gemeni
// edited by Jonas S Karlsson

#include <stdio.h>
#include <conio.h>
#include <string.h>
#include <stdlib.h>

#include "orwin.h"


#define BUF_SIZE 2048

typedef struct APP {
  char* buf;
  int b_len, pos, cx, cy, ins;
  int last;
} APP;

void redraw(APP* state) {
  int i, x = 0, y = 0, pos= state->pos;
  char w, h, *buf= state->buf;

  screensize(&w, &h);

  // TODO: causes flickr, because of attrib
  clrscr();

  // TODO: use while(*p)
  for (i = 0; i < state->b_len; ++i) {
    if (i == pos) { state->cx = x; state->cy = y; }
    if (buf[i] == '\n') {
      x = 0; y++;
      if (y >= h - 1) break;
    } else {
      if (x < w) { gotoxy(x, y); putchar(buf[i]); x++; }
      if (x >= w) { x = 0; y++; }
      if (y >= h - 1) break;
    }
  }

  if (pos == state->b_len) { state->cx = x; state->cy = y; }
  gotoxy(0, h - 1);
  // TODO: goes bad, if toolong...
  printf("--- vi abcdefg");
  //printf("%-15s Pos:%d/%d", state->ins ? "-- INSERT --" : "-- COMMAND --", state->pos, state->b_len);
  gotoxy(state->cx, state->cy);
}

int next_line(APP* state, int p) {
  while (p < state->b_len && state->buf[p] != '\n') p++;
  return (p < state->b_len) ? p + 1 : state->b_len;
}

int prev_line(APP* state, int p) {
  if (p <= 0) return 0;
  p--; if (p > 0 && state->buf[p] == '\n') p--;
  while (p > 0 && state->buf[p-1] != '\n') p--;
  return p;
}

void* app_vi(APP* state, char* line) {
  char c;
  // cached
  char *buf;
  int pos, b_len;

  if (!state) {

    // TODO: combine into one
    state= calloc(sizeof(APP), 1);
    if (!state) return 0;
    state->buf= calloc(BUF_SIZE, 1);
    strcpy(state->buf, "Text\n  to\nedIt,");
    return state;

  } else if (line == CLEANUP) {
    free(state->buf); state->buf= 0;
    return 0;
  }
  
  buf= state->buf;
  pos= state->pos;
  b_len= state->b_len;
  
  if (!buf) return WAITKEY;
		     
  c = getc();
  if (!c) return WAITKEY;
  
  if (state->ins) {
    if (c == 27) { state->ins = 0; if (pos > 0 && buf[pos-1] != '\n') pos--; }
    else if (c == 8 || c == 127) {
      if (pos > 0) { memmove(&buf[pos-1], &buf[pos], b_len - pos); pos--; b_len--; }
    } else if (b_len < BUF_SIZE - 1) {
      memmove(&buf[pos+1], &buf[pos], b_len - pos); buf[pos++] = (c == 13) ? '\n' : c; b_len++;
    }
  } else {
    if (c == 'i') state->ins = 1;
    else if (c == 'h' && pos > 0 && buf[pos-1] != '\n') pos--;
    else if (c == 'l' && pos < b_len && buf[pos] != '\n') pos++;
    else if (c == 'j') pos = next_line(state, pos);
    else if (c == 'k') pos = prev_line(state, pos);
    else if (c == 'x' && pos < b_len && buf[pos] != '\n') {
      memmove(buf+pos, buf+pos+1, b_len - pos - 1);
      b_len--;
    } else if (c == 'd') {
      if (state->last == 'd') {
	int start = prev_line(state, pos + 1), end = next_line(state, pos);
	memmove(buf+start, buf+end, b_len - end);
	b_len -= (end - start); pos = start; state->last = 0;
      }
      goto update;
    } else if (c == 'q') { clrscr(); return WAITKEY; } // TODO: exit

    state->last = 0;
  }

 update:
  state->pos= pos;
  state->b_len= b_len;

  redraw(state);
    
  return WAITKEY;
}
