#!/bin/bash

rm bootdisk.dsk
rm ~/ORIC/bootdisk.dsk

# 1. Compile the assembly file into a standard object block
ca65 bootdisk.asm -o bootdisk.o

# 2. Link using the complete geometry config to produce the full-sized file
ld65 -C bootdisk.cfg bootdisk.o -o bootdisk.dsk

# 3. Clean up the object file
rm bootdisk.o

ls -l bootdisk.dsk

# 4. Convert the valid ORICDISK layout to final MFM format
./old2mfm bootdisk.dsk

ls -l bootdisk.dsk

# 5. Copy to your target testing directory
cp bootdisk.dsk ~/ORIC/

ls -pl ~/ORIC/bootdisk.dsk

