// (only) this file generated by Gemini AI after
// design session with Jonas S Karlsson.
//
// Heavily edited by Jonas S Karlsson

#include <string.h>
#include <stdint.h>

// Fixed global definitions
#define BITSET_BYTES  1024
// % target bit-saturation threshold
#define TARGET_DENSITY  38

// TODO: assert char is unsigned

// default target platform
typedef uint16_t uint;

// Global RAM scratchpad area
char bitset[BITSET_BYTES];

/*
 * 1. LIGHTWEIGHT 13-BIT HYBRID HASH FUNCTION
 * Generates an index from 0 to 8191.
 * Uses a rolling shift-and-add mix that compiles beautifully down
 * to raw A, X, Y register operations on a 6502.
 */
uint hash_trigram(char* str) {
  uint h = 0;
    
  // Process exactly 3 characters (or stop early if null-terminator hit)
  if (*str) { h = (h << 4) ^ *str++; }
  if (*str) { h = (h << 4) ^ *str++; }
  if (*str) { h = (h << 4) ^ *str;   }
    
  return h & 0x1FFF; // Restrict output cleanly to 13 bits (0 to 8191)
}

uint hash_unigram(char* str, unsigned char len) {
  uint h = 5381;
  while (len--) {
    h = ((h << 3) + h) ^ *str++;
  }
  return h & 0x1FFF;
}

uint hash_bigram(uint hash1, uint hash2) {
  // Directional merge: Rotate left 3 bits, then XOR
  uint h = (hash1 << 3) | (hash1 >> 10);
  return (h ^ hash2) & 0x1FFF;
}

// Indexer
//
// Streams through a null-terminated string.
//
// Extracts:
// - trigrams
// - single-word unigrams
// - directional bigrams
//
// setting positional bits in bitset
 
void generate_raw_index(char* text) {
  char *p = text, *wstart = text;
  char wlen = 0;
  uint whash = 0, last_whash = 0;
  uint i;
    
  // Step A: Clear the 1 KB bitset completely
  memset(bitset, 0, BITSET_BYTES);
    
  do {
    // tokenize word tracking spaces/punctuation boundaries
    if (*p > ' ') { 
      // char (TODO: stop non a-z?)
      if (!wlen) wstart = p;
      wlen++;
    } else {
      // \b - word boundary (space, control char, etc.)
      if (wlen > 0) {
	whash = hash_unigram(wstart, wlen);
                
	// Set Unigram Anchor Bit
	bitset[whash >> 3] |= (1 << (whash & 7));
                
	// if have previous word hash sequence!
	if (last_word_hash) {
	  i = hash_bigram(last_whash, whash);
	  bitset[i >> 3] |= (1 << (i & 7));
	}
                
	last_whash = whash;
	wlen = 0;
      }
    }

    // we do test in middle to fold trailing words
    if (!*p) break;
    
    // trigram over sliding window
    i = hash_trigram(p);
    // TODO: lookup table for 6502
    bitset[i >> 3] |= (1 << (i & 7));

    ++p;
  } while (1);
}

// popcount: Counts the '1' in bitset.
// fast, hardware-friendly popcount loop.
uint index_popcount(uint bytes) {
  uint n = 0;
  uint i;
  char b;
    
  for (i = 0; i < bytes; i++) {
    b = bitset[i];
    // Optimized 8-bit lookup-less bit enumeration
    while (b) {
      n += (b & 1);
      b >>= 1;
    }
  }
  return n;
}

// folds bitset upper OR lower till default density,
// or stops at 32 bytes.
uint fold_index(void) {
  uint z = BITSET_BYTES;
  char folds = 0;
  uint bits, density, i, half;

  while (z > 32) {
    bits = index_popcount(z);
    density = (uint)(((unsigned long)bits * 100) / (z * 8));
    // done?
    if (density >= TARGET_DENSITY) break;
        
    // FOLD upper half into lower by ORing
    z>>= 1;
    for (i = 0; i < z; i++) bitset[i] |= bitset[i + z];
    ++folds;
  }
    
  fprintf(stderr, "fold #%d %d%% density %d bytes\n",
	  folds, density, z);

  return folds;
}
