// (only) this file generated by AI after
// design session with Jonas S Karlsson.

#include <string.h>
#include <stdint.h>
#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>

#define BITSET_BYTES  1024
#define MAX_QUERY     1024

#define WORD_WEIGHT   32
#define SEQ_WEIGHT    16
#define FRAG_WEIGHT    1

char idx[BITSET_BYTES];
char query[MAX_QUERY];

uint16_t fold_size;
uint16_t fold_mask;

uint16_t hash_trigram(char* s) {
  uint16_t h = 0;
  char a = s[0], b = s[1], c = s[2];
  if (!isalnum(a) || !isalnum(b) || ((a|b|c)&0x80)) return 0;
  if (!isalnum(c)) c = 0;
  h = (tolower(a) << 4) ^ tolower(b);
  if (c) { h = (h << 4) ^ tolower(c); }
  return h & 0x1FFF;
}

uint16_t hash_unigram(char* s, unsigned char len) {
  uint16_t h = 5381;
  while (len--) h = ((h << 3) + h) ^ tolower(*s++);
  return h & 0x1FFF;
}

uint16_t hash_bigram(uint16_t h1, uint16_t h2) {
  uint16_t h = (h1 << 3) | (h1 >> 10);
  return (h ^ h2) & 0x1FFF;
}

char test_bit(uint16_t h) {
  uint16_t i = (h >> 3) & fold_mask;
  return (idx[i] & (1 << (h & 7))) ? 1 : 0;
}

void pr_case(char* s, int len, char found) {
  int i;
  for (i = 0; i < len; i++) {
    putchar(found ? tolower(s[i]) : toupper(s[i]));
  }
}

// Simple standalone function to test all trigrams in a word
// Updates total score metrics, and prints failures into TriNot stream
void score_word_trigrams(char* s, int len, char parent_found, uint16_t* hits, uint16_t* total) {
  int j;
  uint16_t thash;
  char tok;

  if (len < 3) return;

  for (j = 0; j <= len - 3; j++) {
    thash = hash_trigram(&s[j]);
    if (thash) {
      tok = test_bit(thash);
      
      // ONLY score points if the word unigram actually passed verification
      if (parent_found) {
        *total += FRAG_WEIGHT;
        if (tok) *hits += FRAG_WEIGHT;
      }
      
      // If a trigram is completely missing, log it in upper case
      if (!tok) {
        pr_case(&s[j], 3, 0);
        putchar(' ');
      }
    }
  }
}

int main(int argc, char* argv[]) {
  FILE* f;
  long sz;
  char i, j;
  uint16_t hits = 0, total = 0, whash = 0, last_whash = 0, thash;
  char *p, *wstart;
  char wlen, found, both;
  uint16_t bothhash, pct;

  if (argc < 3) {
    printf("Usage: search <idx_file> <word1> [word2] ...\n");
    return 1;
  }

  if (!(f = fopen(argv[1], "rb"))) {
    printf("%%Error opening %s\n", argv[1]);
    return 1;
  }

  sz = fread(idx, 1, BITSET_BYTES, f);
  fclose(f);

  if (sz > BITSET_BYTES || sz < 32) {
    printf("%%Error: Invalid index size %ld\n", sz);
    return 1;
  }

  fold_size = (uint16_t)sz;
  fold_mask = fold_size - 1;

  // --- RECREATE SINGLE QUERY STRING ---
  query[0] = 0;
  for (i = 2; i < argc; i++) {
    if (strlen(query) + strlen(argv[i]) + 2 >= MAX_QUERY) break;
    if (i > 2) strcat(query, " ");
    strcat(query, argv[i]);
  }

  printf("Search:\t");
  
  // --- SINGLE PASS TRACE LOOP ---
  p = query;
  wstart = query;
  wlen = 0;

  while (1) {

    if (isalnum(*p)) {

      if (!wlen) wstart = p;
      wlen++;

    } else if (wlen > 0) {

      whash = hash_unigram(wstart, wlen);
      found = test_bit(whash);

      // --- SELF-VERIFICATION COUNTER-COLLISION ACTION ---
      // Walk the word's trigrams to confirm it actually exists.
      // If ANY structural trigram fails, the unigram was a false positive!
      if (found && wlen >= 3) {
        for (i = 0; i <= wlen - 3; i++) {
          thash = hash_trigram(&wstart[i]);
          if (thash && !test_bit(thash)) {
            found = 0; // Force false positive down to 0!
            break;
          }
        }
      }

      total += WORD_WEIGHT;
      if (found) hits += WORD_WEIGHT;
      
      both = 0;
      if (last_whash) {
	bothhash = hash_bigram(last_whash, whash);
	total += SEQ_WEIGHT;
	if (test_bit(bothhash)) { hits += SEQ_WEIGHT; both = 1; }
      }
      putchar(both ? '_' : ' ');

      pr_case(wstart, wlen, found);
      
      // Store unigram match status down to gate internal fragment accumulation
      // This will append missing sequences into our print stream cleanly
      if (wlen >= 3) {
        // We print a marker later, so we capture the TriNot text layout inline or below
      }
      
      last_whash = found ? whash : 0;
      wlen = 0;

    }

    // Test at end to terminte last item!
    if (!*p) break;
    p++;
  }

  // --- CLEAN TRI-NOT PRINT OUT ROW ---
  printf("\nTriNot:\t");

  p = query;
  wstart = query;
  wlen = 0;

  while (1) {

    if (isalnum(*p)) {

      if (!wlen) wstart = p;
      wlen++;

    } else if (wlen > 0) {

      whash = hash_unigram(wstart, wlen);
      // Re-verify the target using the exact same isolated logic 
      found = test_bit(whash);
      if (found && wlen >= 3) {
        for (i = 0; i <= wlen - 3; i++) {
          if (!test_bit(hash_trigram(&wstart[i]))) { found = 0; break; }
        }
      }
      score_word_trigrams(wstart, wlen, found, &hits, &total);
      wlen = 0;

    }

    // Test at end to terminte last item!
    if (!*p) break;
    p++;
  }

  pct = total ? (uint16_t)(((unsigned long)hits * 100) / total) : 0;
  printf("\nMatch:\t%u%%\n", pct);

  return 0;
}
