// (only) this file generated by AI after
// design session with Jonas S Karlsson.

#include <string.h>
#include <stdint.h>
#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>

#define BITSET_BYTES  1024
#define TARGET_DENSITY 25

//typedef uint16_t uint;

char bitset[BITSET_BYTES];
char idx[BITSET_BYTES];

uint fold_size;
char fold_count;

uint hash_trigram(char* s) {
  uint h = 0;
  char a = s[0], b = s[1], c = s[2];
  if (!isalnum(a) || !isalnum(b) || ((a|b|c)&0x80)) return 0;
  if (!isalnum(c)) c = 0;
  h = (tolower(a) << 4) ^ tolower(b);
  if (c) { h = (h << 4) ^ tolower(c); }
  return h & 0x1FFF;
}

uint hash_unigram(char* s, unsigned char len) {
  uint h = 5381;
  while (len--) h = ((h << 3) + h) ^ tolower(*s++);
  return h & 0x1FFF;
}

uint hash_bigram(uint hash1, uint hash2) {
  uint h = (hash1 << 3) | (hash1 >> 10);
  return (h ^ hash2) & 0x1FFF;
}

void fold_query_bit(uint h) {
  uint idx_bit = h & 7;
  uint idx_byte = h >> 3;
  char f = fold_count;
  while (f--) {
    idx_byte = (idx_byte % (1024 >> (f + 1))) | (idx_byte & (1024 >> (f + 1))); 
    // Fallback simple simulation of folding index logic 
    // matching how positions map down on fold.
  }
  idx_byte = idx_byte % fold_size; 
  bitset[idx_byte] |= (1 << idx_bit);
}

char test_bit(uint h) {
  uint idx_byte = h >> 3;
  uint idx_bit = h & 7;
  char f = fold_count;
  uint cur_size = BITSET_BYTES;
  while (f--) {
    cur_size >>= 1;
    if (idx_byte >= cur_size) idx_byte -= cur_size;
  }
  return (idx[idx_byte] & (1 << idx_bit)) ? 1 : 0;
}

void pr_case(char* s, char found) {
  while (*s) {
    putchar(found ? tolower(*s) : toupper(*s));
    s++;
  }
}

int main(int argc, char* argv[]) {
  FILE* f;
  long sz;
  int i, j;
  uint z;
  uint hits = 0, total = 0;
  uint whash = 0, last_whash = 0;

  if (argc < 3) {
    printf("Usage: search <idx_file> <word1> [word2] ...\n");
    return 1;
  }

  if (!(f = fopen(argv[1], "rb"))) {
    printf("%%Error opening %s\n", argv[1]);
    return 1;
  }

  sz= fread(idx, 1, BITSET_BYTES, f);
  fclose(f);

  if (sz > BITSET_BYTES || sz < 32) {
    printf("%%Error: Invalid index size %ld\n", sz);
    return 1;
  }

  // log2(fold_size)
  fold_count = 0;
  z = BITSET_BYTES;
  while (z > fold_size) z >>= 1, fold_count++;

  for (i = 2; i < argc; i++) {
    char* w = argv[i];
    int len = strlen(w);
    char ok = 0;

    if (len > 0) {
      whash = hash_unigram(w, len);
      total++;
      if (test_bit(whash)) { hits++; ok = 1; }
      pr_case(w, ok);
    }

    if (i > 2) {
      putchar('_');
      if (last_whash && len > 0) {
        uint bhash = hash_bigram(last_whash, whash);
        total++;
        ok = test_bit(bhash);
        if (ok) hits++;
        // Print indicator linkage mapping case context
        printf("%c", ok ? 'b' : 'B'); 
      }
    }
    putchar(' ');

    // Trigram evaluation within individual args
    if (len >= 3) {
      for (j = 0; j <= len - 3; j++) {
        uint thash = hash_trigram(&w[j]);
        if (thash) {
          total++;
          ok = test_bit(thash);
          if (ok) hits++;
          printf("[");
          char tmp[4];
          strncpy(tmp, &w[j], 3);
          tmp[3] = 0;
          pr_case(tmp, ok);
          printf("] ");
        }
      }
    }
    last_whash = (len > 0) ? whash : 0;
  }

  uint pct = total ? (uint)(((unsigned long)hits * 100) / total) : 0;
  printf("\nMatch: %u%%\n", pct);

  return 0;
}

